Better models
flyingleafe/pyannote-audio pull request #1
Opened 2023-07-12 17:03 UTC by mrkito

Features are extracted once from wavlm

added ECAPA_TDNN_SMALL after  features of trained segmentation  

 pyannote-audio/tutorials/example_wavlm.py - inference

2023-07-18 12:57 UTC, flyingleafe commented
@mrkito Please rebase your commits on top of current `better-models` for ease of review

2023-07-26 10:26 UTC, flyingleafe requested changes
1. Пожалуйста, ребейзнись на текущий HEAD `better-models` и форспушни, чтобы в PR не было видно моих коммитов
2. Пожалуйста, сделай получение wavlm фичей (а также определение того что мы ими пользуемся) более явными и читаемыми

Также см. все прочие комментарии

2023-07-26 10:26 UTC, flyingleafe commented on pyannote/audio/models/embedding/ecapa_tdnn.py
> +class Res2Conv1dReluBn(nn.Module):
Можно было взять имплементацию из speechbrain, передав нужные параметры, он все равно есть как зависимость в pyannote и так

2023-07-26 10:26 UTC, flyingleafe commented on pyannote/audio/models/segmentation/PyanNet.py
> +        return torch.cat([segmetation, feats], -1)
Если уж решил возвращать фичи прямо в методе forward этой модели и таким образом менять формат возвращаемого значения, то почему именно таким странным образом? мог бы просто вернуть пару тензоров

2023-07-26 10:26 UTC, flyingleafe commented on pyannote/audio/pipelines/speaker_diarization.py
> +            segmentations.data = segmentations.data[:, :, :segmentations_classes]
Еще более странный способ проверить, использует ли наш пайплайн wavlm фичи. Можно ли сделать это как-то более явно и читабельно?

2023-07-26 10:26 UTC, flyingleafe commented on pyannote/audio/pipelines/speaker_verification.py
> +        imasks = masks > 0.5
Зачем была удалена вся эта логика здесь? Для ее присутствия у автора pyannote явно были какие-то причины

2023-07-26 10:26 UTC, flyingleafe commented on tutorials/example_wavlm.py
> +default_pipeline("../tests/data/dev00.wav", return_embeddings=True)
Можно ли это написать именно как pytest? (можно ничего не ассертить, а просто чтобы тест проходил если не выбрасывается исключение

2023-07-26 10:26 UTC, flyingleafe commented on tutorials/example_wavlm.py
> +                                            use_auth_token=os.environ['TOKEN_HUGGINFACE'])
Можно ли проинициализировать это не скачивая бессмысленно pretrained модель, а напрямую вызвав конструктор `SpeakerDiarization`, явно передав в него аргументы (сегментационная и эмбеддинг модели выше)?

2023-07-26 12:09 UTC, mrkito commented on pyannote/audio/pipelines/speaker_diarization.py
> +            segmentations.data = segmentations.data[:, :, :segmentations_classes]
да, могу сделать аргументом

2023-07-26 12:10 UTC, mrkito commented on pyannote/audio/models/segmentation/PyanNet.py
> +        return torch.cat([segmetation, feats], -1)
нет, там есть проверка

2023-07-26 12:10 UTC, mrkito commented on pyannote/audio/models/embedding/ecapa_tdnn.py
> +class Res2Conv1dReluBn(nn.Module):
могу

2023-07-26 12:12 UTC, mrkito commented on tutorials/example_wavlm.py
> +                                            use_auth_token=os.environ['TOKEN_HUGGINFACE'])
да. знаю как сделать, но надо :

-  аккуратно  ребейзнуть оригинальный pyannnote
- явно передать в него аргументы

2023-07-26 12:12 UTC, mrkito commented on tutorials/example_wavlm.py
> +default_pipeline("../tests/data/dev00.wav", return_embeddings=True)
можно

2023-07-26 12:12 UTC, mrkito commented on pyannote/audio/pipelines/speaker_verification.py
> +        imasks = masks > 0.5
могу пофиксить , надо немножко переписать

2023-07-26 12:15 UTC, mrkito commented on pyannote/audio/models/segmentation/PyanNet.py
> +        return torch.cat([segmetation, feats], -1)
надо модифицировать код так чтобы не сломался оригинальный

2023-07-26 12:16 UTC, mrkito commented on tutorials/example_wavlm.py
> +                                            use_auth_token=os.environ['TOKEN_HUGGINFACE'])
а то сложно будет поддерживать новую версию

2025-10-26 18:48 UTC, closed without merging